- apt: pkg=nginx-light
- lineinfile: dest=/etc/nginx/nginx.conf regexp="^\s*#? ?server_tokens" line="server_tokens off;"
  register: config
- service: name=nginx state=restarted
  when: config.changed
- file: path={{ www }}/index.nginx-debian.html state=absent
- template: src=index.html dest={{ www }}/index.html
- copy: src=robots.txt dest={{ www }}/robots.txt
