- file: path=/etc/exit.d state=directory
- file: path=/opt/exit state=directory
- copy: src=exit.js dest=/opt/exit/exit.js mode=0755
  register: server
- copy: src=allow.py dest=/opt/exit/allow.py mode=0755
- copy: src=reload.sh dest=/etc/cron.daily/exit mode=0755
- unarchive: src=exit.d.tar.xz dest=/etc
  register: rules
- shell: /etc/cron.daily/exit
  when: rules.changed
- copy: src=exit.service dest=/etc/systemd/system/exit.service
- service: name=exit state=restarted
  when: server.changed
- file: src=../exit.service dest=/etc/systemd/system/multi-user.target.wants/exit.service state=link
- service: name=exit state=started
